---

- name: Add tmp cleanup at reboot
  lineinfile:
    dest:   '/etc/default/rcS'
    regexp: '^#?TMPTIME=0'
    line:   'TMPTIME=0'

- name: Update boot settings (disable console screensaver, enable zswap)
  lineinfile:
    dest:   '/etc/default/grub'
    regexp: '{{ item.regexp }}'
    line:   '{{ item.line }}'
  with_items:
   - { regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=', line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet consoleblank=0 zswap.enabled=1"' }
   - { regexp: '^GRUB_TIMEOUT=', line: 'GRUB_TIMEOUT=0' }
   - { regexp: '^GRUB_HIDDEN_TIMEOUT=', line: 'GRUB_TIMEOUT=0' }
  notify:
    - Update grub

# https://en.wikipedia.org/wiki/Zswap
# https://askubuntu.com/a/361321
- name: Immediately enable zswap (if available)
  shell: echo 1 > /sys/module/zswap/parameters/enabled
  ignore_errors: yes

- name: Setup System Hostname
  hostname:
    name: DEV-VM

- name: Setup hosts
  lineinfile:
    dest:   '/etc/hosts'
    regexp: 'DEVELOPMENT-VM'
    line:   '127.0.0.1 DEVELOPMENT-VM DEV-VM'
    owner:  root
    group:  root
    mode:   0644
