---

- name: Prepare docker.service.d placeholder
  file:
    path:    /etc/systemd/system/docker.service.d
    state:   directory
    recurse: yes
    mode:    0775

- name: Apply custom docker service opts
  template:
    src:   templates/docker.service.j2
    dest:  /etc/systemd/system/docker.service.d/custom-opts.conf
    owner: vagrant
    group: root
    mode:  0664
  notify:
    - Restart Docker

- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest

#############################
# Apparmor profile
#############################

- name: Fix AppArmor profile
  lineinfile:
    dest:        '/etc/apparmor.d/docker'
    insertafter: '[\s]*capability'
    line:        '  ptrace peer=docker-default,'
    state:       present
  ignore_errors: True
  notify:
    - Reload AppArmor

#############################
# User
#############################

- name: Add vagrant to docker group
  user:
    name:   'vagrant'
    groups: 'docker'
    append: yes
